### ISSUE TITLE
Socratic Seminar 36 (December 2024)

### ISSUE THREAD

**Issue by Randy808** [Bitcoin-Grove/miamibitdevs.org#13]

**Comment by Randy808** [comment]
A proposal for non-custodial ecash
https://gist.github.com/lukechilds/307341239beac72c9d8cfe3198f9bfff

**Comment by Randy808** [comment]
CTV, APO, CAT activity on signet
https://delvingbitcoin.org/t/ctv-apo-cat-activity-on-signet/1257

**Comment by Randy808** [comment]
Mitigating Replacement Cycling Attacks with some magic
https://world.hey.com/mpch/mitigating-replacement-cycling-attacks-with-some-magic-part-i-4a76ad45

**Comment by RazTeve** [comment]
Un-FE’d Covenants:
https://rubin.io/public/pdfs/unfedcovenants.pdf

**Comment by RazTeve** [comment]
bitsacco:
https://blog.bitsacco.com/the-bitsacco-template/

**Comment by Randy808** [comment]
Softfork initiative for CTV announced by CobraBitcoin
https://x.com/CobraBitcoin/status/1863006822048669961

**Comment by Randy808** [comment]
Covenants support list
https://en.bitcoin.it/wiki/Covenants_support

**Comment by RazTeve** [comment]
Prisms:
https://www.roygbiv.guide/v4v/

[Diagram](https://viewer.diagrams.net/index.html?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=v4v-bolt12-prism.drawio#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Ffarscapian%2Froygbiv%2Fmain%2Fv4v-bolt12-prism.drawio#%7B%22pageId%22%3A%225v8HJ1yWOcfsFn8PfRNU%22%7D)

**Comment by luisschwab** [comment]
Round Robin Cashu Mint Auditor
https://audit.8333.space/

**Comment by luisschwab** [comment]
Boost Your Bitcoin Node Sync With UTXO Snapshots
https://blog.lopp.net/bitcoin-node-sync-with-utxo-snapshots/
