### ISSUE TITLE
Socratic Seminar 30 (June 2024)

### ISSUE THREAD

**Issue by Randy808** [Bitcoin-Grove/miamibitdevs.org#7]

**Comment by RazTeve** [comment]
Chain Swaps https://blog.boltz.exchange/p/dispatching-chain-swaps

**Comment by RazTeve** [comment]
BIP merged https://github.com/bitcoin/bips/blob/master/bip-0431.mediawiki

**Comment by Randy808** [comment]
GrassFedBitcoin on empty blocks and Antpool/Bitmain fuckery
https://stacker.news/items/557126

**Comment by Randy808** [comment]
FE’d Up Covenants
https://rubin.io/public/pdfs/fedcov.pdf

**Comment by RazTeve** [comment]
ecash desktop wallet for better Bitcoin privacy https://blog.mutinywallet.com/harbor/

**Comment by RazTeve** [comment]
silent payments https://bitcoinops.org/en/topics/silent-payments/

**Comment by Randy808** [comment]
Introducing Ark V2
https://brqgoo.medium.com/introducing-ark-v2-2e7ab378e87b

QuBit - P2QRH spending rules
https://github.com/cryptoquick/bips/blob/p2qrh/bip-p2qrh.mediawiki

**Comment by RazTeve** [comment]
![image](https://github.com/Bitcoin-Grove/miamibitdevs.org/assets/80485118/9b4ddd73-f988-4f9d-9c63-a46ad5eba871)

**Comment by RazTeve** [comment]
https://bitcoindevs.xyz/
