### ISSUE TITLE
Socratic Seminar 31 (July 2024)

### ISSUE THREAD

**Issue by Randy808** [Bitcoin-Grove/miamibitdevs.org#8]

**Comment by Randy808** [comment]
Introducing Brollups
https://brqgoo.medium.com/introducing-brollups-18ec4081f6e7

Fedimint guardian's domain seized by registrar
https://primal.net/e/note1luc96j5l8dm33zqzly40y9ygfxjfxj2q2qr6264rcna8uzxk4s6ql2ngwg

**Comment by RazTeve** [comment]
CUSF https://bip300cusf.com/

**Comment by RazTeve** [comment]
bitcoin, the stable coin https://x.com/SteveSimple/status/1808127741822156884

**Comment by RazTeve** [comment]
op_cat https://blog.blockstream.com/op_cat-the-purr-fect-solution-for-covenants/

**Comment by RazTeve** [comment]
bolt12 https://bolt12.org/

**Comment by Randy808** [comment]
Script State From Lamport Signatures
https://blog.blockstream.com/script-state-from-lamport-signatures/

**Comment by dka218** [comment]
Empty block report
https://research.mempool.space/empty-block-report/

**Comment by dka218** [comment]
Bitcoin Core 27.1 released
https://groups.google.com/g/bitcoindev/c/9D-H6SLRsgY
